/*
-- Query: SELECT * FROM fyp.HIS
LIMIT 0, 1000

-- Date: 2023-09-22 13:47
*/
CREATE TABLE HIS (
    patient_id INT PRIMARY KEY,
    name VARCHAR(255),
    date_of_birth DATE,
    gender VARCHAR(10),
    marital_status VARCHAR(20),
    address VARCHAR(255),
    city VARCHAR(100),
    area VARCHAR(100),
    zip_code VARCHAR(20),
    country VARCHAR(100),
    nationality VARCHAR(100),
    phone_number VARCHAR(20),
    email_address VARCHAR(255),
    insurance_provider VARCHAR(255),
    insurance_id VARCHAR(50)
);
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (1,'Lim Wei Ting','1994-08-17','Female','Single','123 Bukit Timah Rd','Singapore','Bukit Timah','229837','Singapore','Singaporean','+65 9123 4567','lim@example.com','AIA Singapore','AIA123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (2,'Chen Wei Jun','1982-05-23','Male','Married','456 Clementi Ave','Singapore','Clementi','120456','Singapore','Singaporean','+65 9876 5432','chen@example.com','Prudential Singapore','PS456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (3,'Rajesh Kumar','1977-02-11','Male','Married','789 Little India Rd','Singapore','Little India','218733','Singapore','Singaporean','+65 8765 4321','rajesh@example.com','Manulife Singapore','MF789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (4,'Ng Mei Ling','1991-10-05','Female','Divorced','111 Toa Payoh St 21','Singapore','Toa Payoh','678910','Singapore','Singaporean','+65 7654 3210','ng@example.com','AXA Singapore','AXA987');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (5,'Tan Ah Kow','1989-07-03','Male','Single','345 East Coast Rd','Singapore','East Coast','428981','Singapore','Singaporean','+65 9321 5432','tanahkow@example.com','Aviva Singapore','AV123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (6,'Muthu Kumar','1984-12-25','Male','Married','567 Serangoon Rd','Singapore','Serangoon','218890','Singapore','Singaporean','+65 8222 3344','muthu@example.com','Tokio Marine Singapore','TM456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (7,'Wong Siew Leng','1993-09-09','Female','Single','789 Jurong West St 51','Singapore','Jurong West','649123','Singapore','Singaporean','+65 6333 4455','wongsl@example.com','MSIG Singapore','MSIG123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (8,'Jasmine Lee','1981-06-02','Female','Married','123 Hougang Ave','Singapore','Hougang Ave','530123','Singapore','Singaporean','+65 8111 2233','jasmine@example.com','Allianz Singapore','AL123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (9,'Abdul Rahman','1976-03-14','Male','Divorced','456 Woodlands Dr','Singapore','Woodlands','730456','Singapore','Singaporean','+65 9000 1001','abdul@example.com','AXA Singapore','AXA789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (10,'Cheng Wei Ting','1990-11-07','Female','Single','789 Bukit Batok St 21','Singapore','Bukit Batok','659837','Singapore','Singaporean','+65 9777 8888','cheng@example.com','Great Eastern','GE123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (11,'Nizar Bin Ahmad','1983-08-20','Male','Married','123 Yishun Ave','Singapore','Yishun','760456','Singapore','Singaporean','+65 9444 3333','nizar@example.com','NTUC Income','NTUC123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (12,'Linda Lim','1995-05-13','Female','Single','456 Queenstown Rd','Singapore','Queenstown','120837','Singapore','Singaporean','+65 9333 2222','linda@example.com','Prudential Singapore','PS789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (13,'Mohan Raj','1979-02-27','Male','Married','789 Geylang Rd','Singapore','Geylang','218777','Singapore','Singaporean','+65 9111 0000','mohan@example.com','Manulife Singapore','MF123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (14,'Lim Ah Beng','1986-10-10','Male','Single','123 Orchard Blvd','Singapore','Orchard','238837','Singapore','Singaporean','+65 9777 9999','limahbeng@example.com','AIA Singapore','AIA789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (15,'Siti Rahmah','1987-07-22','Female','Divorced','456 Sengkang Ave','Singapore','Sengkang','120123','Singapore','Singaporean','+65 9888 7777','siti@example.com','Great Eastern','GE456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (16,'David Tan','1996-04-15','Male','Single','789 Holland Rd','Singapore','Holland','279837','Singapore','Singaporean','+65 9111 2222','david@example.com','NTUC Income','NTUC456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (17,'Sonia Lee','1988-01-08','Female','Married','123 Tampines St','Singapore','Tampines','520456','Singapore','Singaporean','+65 9333 4444','sonia@example.com','Prudential Singapore','PS123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (18,'Mohammed Ahmed','1982-10-01','Male','Married','456 Pasir Ris Rd','Singapore','Pasir Ris','518837','Singapore','Singaporean','+65 9444 5555','mohammed@example.com','Tokio Marine Singapore','TM123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (19,'Lily Ng','1990-07-24','Female','Single','789 Ang Mo Kio Ave','Singapore','Ang Mo Kio','560123','Singapore','Singaporean','+65 9555 6666','lily@example.com','Aviva Singapore','AV789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (20,'William Tan','1978-04-16','Male','Married','123 Bukit Panjang Rd','Singapore','Bukit Panjang','680456','Singapore','Singaporean','+65 9222 7777','william@example.com','Allianz Singapore','AL456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (21,'Rahim Bin Abdul','1984-01-19','Male','Divorced','456 Bedok Rd','Singapore','Bedok','469837','Singapore','Singaporean','+65 9333 8888','rahim@example.com','MSIG Singapore','MSIG456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (22,'Emily Johnson','1990-08-15','Female','Single','123 Elm St','New York','NY','10001','USA','American','+1 555-123-4567','emily@example.com','Blue Cross','BC123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (23,'Mark Thompson','1982-05-25','Male','Married','456 Oak Ave','Los Angeles','CA','90001','USA','American','+1 555-987-6543','mark@example.com','UnitedHealthcare','UHC456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (24,'Sophie Martin','1977-03-18','Female','Married','789 Maple Rd','Chicago','IL','60601','USA','American','+1 555-555-5555','sophie@example.com','Aetna','AE789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (25,'Carlos Sanchez','1992-10-05','Male','Single','111 Pine St','Miami','FL','33101','USA','American','+1 555-765-4321','carlos@example.com','Cigna','CI123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (26,'Elena Rodriguez','1989-07-03','Female','Single','345 Palm Rd','Houston','TX','77001','USA','American','+1 555-932-1546','elena@example.com','Humana','HU789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (27,'David Smith','1984-12-25','Male','Married','567 Cedar St','San Francisco','CA','94101','USA','American','+1 555-824-3333','david@example.com','Kaiser Permanente','KP123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (28,'Anastasia Ivanova','1993-09-09','Female','Single','789 Birch Ave','Seattle','WA','98101','USA','American','+1 555-633-4455','anastasia@example.com','Molina Healthcare','MH789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (29,'William Jones','1981-06-02','Male','Married','123 Ash St','Boston','MA','02101','USA','American','+1 555-811-2233','william@example.com','Anthem','AN123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (30,'Maria Garcia','1976-03-14','Female','Divorced','456 Elmwood Ave','Detroit','MI','48201','USA','American','+1 555-900-1001','maria@example.com','Centene Corporation','CC456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (31,'Alexandra Petrov','1990-11-07','Female','Single','789 Magnolia St','Denver','CO','80201','USA','American','+1 555-977-8888','alexandra@example.com','Molina Healthcare','MH123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (32,'Joseph Murphy','1983-08-20','Male','Married','123 Redwood Rd','Phoenix','AZ','85001','USA','American','+1 555-944-3333','joseph@example.com','Blue Cross','BC456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (33,'Natalia Kuznetsova','1995-05-13','Female','Single','456 Walnut St','Las Vegas','NV','89101','USA','American','+1 555-933-2222','natalia@example.com','Aetna','AE123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (34,'Daniel Lee','1979-02-27','Male','Married','789 Spruce Rd','Miami','FL','33101','USA','American','+1 555-911-0000','daniel@example.com','UnitedHealthcare','UHC123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (35,'Liam O\'Connor','1986-10-10','Male','Single','123 Pineapple St','Honolulu','HI','96801','USA','American','+1 555-977-9999','liam@example.com','Cigna','CI456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (36,'Isabella Martinez','1987-07-22','Female','Divorced','456 Coconut Ave','Orlando','FL','32801','USA','American','+1 555-988-7777','isabella@example.com','Humana','HU123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (37,'Michael Brown','1996-04-15','Male','Single','789 Mango Rd','New Orleans','LA','70112','USA','American','+1 555-911-2222','michael@example.com','Anthem','AN456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (38,'Olga Petrova','1988-01-08','Female','Married','123 Banana St','San Diego','CA','92101','USA','American','+1 555-944-4444','olga@example.com','Kaiser Permanente','KP456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (39,'Mohammed Ahmed','1982-10-01','Male','Married','456 Papaya Rd','Chicago','IL','60601','USA','American','+1 555-944-5555','mohammed@example.com','Centene Corporation','CC123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (40,'Lily Johnson','1990-07-24','Female','Single','789 Strawberry St','Los Angeles','CA','90001','USA','American','+1 555-955-6666','lily@example.com','Molina Healthcare','MH456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (41,'Christopher Smith','1978-04-16','Male','Married','123 Blueberry St','New York','NY','10001','USA','American','+1 555-9222 7777','christopher@example.com','Blue Cross','BC789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (42,'Tan Wei Jun','1995-08-17','Male','Single','123 Bukit Timah Rd','Singapore','Bukit Timah','229837','Singapore','Singaporean','+65 9123 4567','tan@example.com','AIA Singapore','AIA123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (43,'Leong Siew Ling','1983-05-23','Female','Married','456 Clementi Ave','Singapore','Clementi','120456','Singapore','Singaporean','+65 9876 5432','leong@example.com','Prudential Singapore','PS456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (44,'Lim Ah Hock','1978-03-18','Male','Married','789 Little India Rd','Singapore','Little India','218733','Singapore','Singaporean','+65 8765 4321','limahhock@example.com','NTUC Income','NTUC789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (45,'Kumar Rajesh','1990-10-05','Male','Single','111 Toa Payoh St 21','Singapore','Toa Payoh','678910','Singapore','Singaporean','+65 7654 3210','kumar@example.com','Great Eastern','GE987');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (46,'Ang Wei Ting','1986-07-03','Female','Single','345 East Coast Rd','Singapore','East Coast','428981','Singapore','Singaporean','+65 9321 5432','ang@example.com','Aviva Singapore','AV123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (47,'Muthu Kumar','1994-12-25','Male','Married','567 Serangoon Rd','Singapore','Serangoon','218890','Singapore','Singaporean','+65 8222 3344','muthu@example.com','Tokio Marine Singapore','TM456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (48,'Soh Siew Leng','1982-09-09','Female','Single','789 Jurong West St 51','Singapore','Jurong West','649123','Singapore','Singaporean','+65 6333 4455','soh@example.com','MSIG Singapore','MSIG123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (49,'Lee Mei Ling','1975-06-02','Female','Married','123 Hougang Ave','Singapore','Hougang','530123','Singapore','Singaporean','+65 8111 2233','lee@example.com','Allianz Singapore','AL123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (50,'Tan Ah Beng','1993-03-14','Male','Divorced','456 Woodlands Dr','Singapore','Woodlands','730456','Singapore','Singaporean','+65 9000 1001','tanahbeng@example.com','AXA Singapore','AXA789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (51,'Chia Wei Ting','1980-11-07','Female','Single','789 Bukit Batok St 21','Singapore','Bukit Batok','659837','Singapore','Singaporean','+65 9777 8888','chia@example.com','Great Eastern','GE123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (52,'Lau Mei Ling','1985-10-20','Female','Single','123 Yishun Ave','Singapore','Yishun','760456','Singapore','Singaporean','+65 9444 3333','lau@example.com','NTUC Income','NTUC123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (53,'Lim Siew Leng','1991-01-13','Female','Married','456 Queenstown Rd','Singapore','Queenstown','120837','Singapore','Singaporean','+65 9333 2222','limsl@example.com','Prudential Singapore','PS789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (54,'Koh Wei Jun','1987-02-27','Male','Married','789 Geylang Rd','Singapore','Geylang','218777','Singapore','Singaporean','+65 9111 0000','koh@example.com','Manulife Singapore','MF123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (55,'Tan Ah Keng','1989-10-10','Male','Single','123 Orchard Blvd','Singapore','Orchard','238837','Singapore','Singaporean','+65 9777 9999','tanahkeng@example.com','AIA Singapore','AIA789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (56,'Ng Siew Leng','1986-07-22','Female','Divorced','456 Sengkang Ave','Singapore','Sengkang','120123','Singapore','Singaporean','+65 9888 7777','ngsl@example.com','Great Eastern','GE456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (57,'David Tan','1997-04-15','Male','Single','789 Holland Rd','Singapore','Holland','279837','Singapore','Singaporean','+65 9111 2222','david@example.com','NTUC Income','NTUC456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (58,'Lim Siew Mei','1989-01-08','Female','Married','123 Tampines St','Singapore','Tampines','520456','Singapore','Singaporean','+65 9333 4444','limsm@example.com','Prudential Singapore','PS123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (59,'Ahmad Bin Mohammed','1983-10-01','Male','Married','456 Pasir Ris Rd','Singapore','Pasir Ris','518837','Singapore','Singaporean','+65 9444 5555','ahmad@example.com','Tokio Marine Singapore','TM123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (60,'Chong Wei Ting','1994-07-24','Female','Single','789 Ang Mo Kio Ave','Singapore','Ang Mo Kio','560123','Singapore','Singaporean','+65 9555 6666','chong@example.com','Aviva Singapore','AV789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (61,'Tan Wei Jun','1976-04-16','Male','Married','123 Bukit Panjang Rd','Singapore','Bukit Panjang','680456','Singapore','Singaporean','+65 9222 7777','tanwj@example.com','Allianz Singapore','AL456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (62,'Ahmad Bin Rahim','1990-01-19','Male','Divorced','456 Bedok Rd','Singapore','Bedok','469837','Singapore','Singaporean','+65 9333 8888','ahmadrahim@example.com','MSIG Singapore','MSIG456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (63,'Lim Siew Hock','1985-08-15','Male','Single','123 Orchard Rd','Singapore','Orchard','238879','Singapore','Singaporean','+65 9123 4567','limsh@example.com','AIA Singapore','AIA123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (64,'Koh Wei Jun','1982-05-23','Male','Married','456 Clementi Ave','Singapore','Clementi','120456','Singapore','Singaporean','+65 9876 5432','kohwj@example.com','Prudential Singapore','PS456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (65,'Teo Mei Ling','1977-03-18','Female','Married','789 Little India Rd','Singapore','Little India','218733','Singapore','Singaporean','+65 8765 4321','teo@example.com','NTUC Income','NTUC789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (66,'Chen Wei Ting','1992-10-05','Female','Single','111 Toa Payoh St 21','Singapore','Toa Payoh','678910','Singapore','Singaporean','+65 7654 3210','chenwt@example.com','Great Eastern','GE987');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (67,'Tan Ah Hock','1989-07-03','Male','Single','345 East Coast Rd','Singapore','East Coast','428981','Singapore','Singaporean','+65 9321 5432','tanahhock@example.com','Aviva Singapore','AV123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (68,'Muthu Kumar','1984-12-25','Male','Married','567 Serangoon Rd','Singapore','Serangoon','218890','Singapore','Singaporean','+65 8222 3344','muthu@example.com','Tokio Marine Singapore','TM456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (69,'Soh Siew Leng','1993-09-09','Female','Single','789 Jurong West St 51','Singapore','Jurong West','649123','Singapore','Singaporean','+65 6333 4455','sohsl@example.com','MSIG Singapore','MSIG123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (70,'Tan Wei Jun','1981-06-02','Female','Married','123 Hougang Ave','Singapore','Hougang','530123','Singapore','Singaporean','+65 8111 2233','tanwj@example.com','Allianz Singapore','AL123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (71,'Rajesh Kumar','1976-03-14','Male','Divorced','456 Woodlands Dr','Singapore','Woodlands','730456','Singapore','Singaporean','+65 9000 1001','rajesh@example.com','AXA Singapore','AXA789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (72,'Ang Wei Ting','1990-11-07','Female','Single','789 Bukit Batok St 21','Singapore','Bukit Batok','659837','Singapore','Singaporean','+65 9777 8888','angwt@example.com','Great Eastern','GE123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (73,'Ethan Tan','2000-08-17','Male','Single','123 Orchard Rd','Singapore','Orchard','238879','Singapore','Singaporean','+65 9123 4567','ethan@example.com','AIA Singapore','AIA123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (74,'Olivia Lee','2001-05-23','Female','Single','456 Marina Blvd','Singapore','Marina','120456','Singapore','Singaporean','+65 9876 5432','olivia@example.com','Prudential Singapore','PS456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (75,'Noah Lim','2002-03-18','Male','Single','789 River Rd','Singapore','River','218733','Singapore','Singaporean','+65 8765 4321','noah@example.com','NTUC Income','NTUC789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (76,'Sophia Ng','2003-10-05','Female','Single','111 Clementi St 21','Singapore','Clementi','678910','Singapore','Singaporean','+65 7654 3210','sophia@example.com','Great Eastern','GE987');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (77,'Liam Tan','2004-07-03','Male','Single','345 Bukit Timah Rd','Singapore','Bukit Timah','428981','Singapore','Singaporean','+65 9321 5432','liam@example.com','Aviva Singapore','AV123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (78,'Emma Wong','2005-12-25','Female','Single','567 Serangoon Ave','Singapore','Serangoon','218890','Singapore','Singaporean','+65 8222 3344','emma@example.com','Tokio Marine Singapore','TM456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (79,'Aiden Koh','2006-09-09','Male','Single','789 Jurong West St 51','Singapore','Jurong West','649123','Singapore','Singaporean','+65 6333 4455','aiden@example.com','MSIG Singapore','MSIG123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (80,'Mia Tan','2007-06-02','Female','Single','123 Yishun Ave','Singapore','Yishun','530123','Singapore','Singaporean','+65 8111 2233','mia@example.com','Allianz Singapore','AL123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (81,'Liam Raj','2008-03-14','Male','Single','456 Woodlands Dr','Singapore','Woodlands','730456','Singapore','Singaporean','+65 9000 1001','liamraj@example.com','AXA Singapore','AXA789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (82,'Olivia Chong','2009-11-07','Female','Single','789 Bukit Batok St 21','Singapore','Bukit Batok','659837','Singapore','Singaporean','+65 9777 8888','oliviachong@example.com','Great Eastern','GE123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (83,'Noah Lee','2010-10-20','Male','Single','123 Serangoon Rd','Singapore','Serangoon','760456','Singapore','Singaporean','+65 9444 3333','noahlee@example.com','NTUC Income','NTUC123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (84,'Sophia Tan','2011-01-13','Female','Single','456 Queenstown Rd','Singapore','Queenstown','120837','Singapore','Singaporean','+65 9333 2222','sophiatan@example.com','Prudential Singapore','PS789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (85,'Aiden Lim','2012-02-27','Male','Single','789 Geylang Rd','Singapore','Geylang','218777','Singapore','Singaporean','+65 9111 0000','aidenlim@example.com','Manulife Singapore','MF123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (86,'Mia Tan','2013-10-10','Female','Single','123 Orchard Blvd','Singapore','Orchard','238837','Singapore','Singaporean','+65 9777 9999','miatan@example.com','AIA Singapore','AIA789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (87,'Liam Ng','2014-07-22','Male','Single','456 Sengkang Ave','Singapore','Sengkang','120123','Singapore','Singaporean','+65 9888 7777','liamng@example.com','Great Eastern','GE456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (88,'Emma Lee','2015-04-15','Female','Single','789 Holland Rd','Singapore','Holland','279837','Singapore','Singaporean','+65 9111 2222','emmalee@example.com','NTUC Income','NTUC456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (89,'Aiden Tan','2016-01-08','Male','Single','123 Tampines St','Singapore','Tampines','520456','Singapore','Singaporean','+65 9333 4444','aidentan@example.com','Prudential Singapore','PS123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (90,'Mia Koh','2017-10-01','Female','Single','456 Pasir Ris Rd','Singapore','Pasir Ris','518837','Singapore','Singaporean','+65 9444 5555','miakoh@example.com','Tokio Marine Singapore','TM123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (91,'Liam Tan','2018-07-24','Male','Single','789 Ang Mo Kio Ave','Singapore','Ang Mo Kio','560123','Singapore','Singaporean','+65 9555 6666','liamtan@example.com','Aviva Singapore','AV789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (92,'Olivia Lim','2019-04-16','Female','Single','123 Bukit Panjang Rd','Singapore','Bukit Panjang','680456','Singapore','Singaporean','+65 9222 7777','olivialim@example.com','Allianz Singapore','AL456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (93,'Ella Tan','2022-12-15','Female','Single','123 Orchard Rd','Singapore','Orchard','238879','Singapore','Singaporean','+65 9123 4567','ella@example.com','AIA Singapore','AIA123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (94,'Owen Lee','2022-11-23','Male','Single','456 Marina Blvd','Singapore','Marina','120456','Singapore','Singaporean','+65 9876 5432','owen@example.com','Prudential Singapore','PS456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (95,'Zoe Ng','2022-10-18','Female','Single','789 Little India Rd','Singapore','Little India','218733','Singapore','Singaporean','+65 8765 4321','zoe@example.com','NTUC Income','NTUC789');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (96,'Lucas Lee','2022-09-05','Male','Single','111 Clementi St 21','Singapore','Clementi','678910','Singapore','Singaporean','+65 7654 3210','lucas@example.com','Great Eastern','GE987');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (97,'Aria Tan','2022-08-03','Female','Single','345 Bukit Timah Rd','Singapore','Bukit Timah','428981','Singapore','Singaporean','+65 9321 5432','aria@example.com','Aviva Singapore','AV123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (98,'Liam Wong','2022-07-25','Male','Single','567 Serangoon Ave','Singapore','Serangoon','218890','Singapore','Singaporean','+65 8222 3344','liamwong@example.com','Tokio Marine Singapore','TM456');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (99,'Mia Koh','2022-06-09','Female','Single','789 Jurong West St 51','Singapore','Jurong West','649123','Singapore','Singaporean','+65 6333 4455','mia@example.com','MSIG Singapore','MSIG123');
INSERT INTO `HIS` (`patient_id`,`name`,`date_of_birth`,`gender`,`marital_status`,`address`,`city`,`area`,`zip_code`,`country`,`nationality`,`phone_number`,`email_address`,`insurance_provider`,`insurance_id`) VALUES (100,'Noah Tan','2022-05-02','Male','Single','123 Yishun Ave','Singapore','Yishun','530123','Singapore','Singaporean','+65 8111 2233','noah@example.com','Allianz Singapore','AL123');
